//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfflineProcessing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollegeDBContext : DbContext
    {
        public CollegeDBContext()
            : base("name=CollegeDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EntityPhoneInfo> EntityPhoneInfoes { get; set; }
        public DbSet<EntityWebsiteInfo> EntityWebsiteInfoes { get; set; }
        public DbSet<LocationType> LocationTypes { get; set; }
        public DbSet<NearbyPlace> NearbyPlaces { get; set; }
        public DbSet<CollegeInfo> CollegeInfoes { get; set; }
        public DbSet<DepartmentInfo> DepartmentInfoes { get; set; }
    }
}
