//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeInfo
    {
        public CollegeInfo()
        {
            this.EntityPhoneInfoes = new HashSet<EntityPhoneInfo>();
            this.EntityWebsiteInfoes = new HashSet<EntityWebsiteInfo>();
            this.NearbyPlaces = new HashSet<NearbyPlace>();
            this.DepartmentInfoes = new HashSet<DepartmentInfo>();
            this.tagtables = new HashSet<tagtable>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Principal_Name { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string BankAccount { get; set; }
        public string BankName { get; set; }
    
        public virtual ICollection<EntityPhoneInfo> EntityPhoneInfoes { get; set; }
        public virtual ICollection<EntityWebsiteInfo> EntityWebsiteInfoes { get; set; }
        public virtual ICollection<NearbyPlace> NearbyPlaces { get; set; }
        public virtual ICollection<DepartmentInfo> DepartmentInfoes { get; set; }
        public virtual ICollection<tagtable> tagtables { get; set; }
    }
}
