//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationType
    {
        public LocationType()
        {
            this.NearbyPlaces = new HashSet<NearbyPlace>();
        }
    
        public string LType { get; set; }
    
        public virtual ICollection<NearbyPlace> NearbyPlaces { get; set; }
    }
}
