//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tagtable
    {
        public string Id { get; set; }
        public string TagValue { get; set; }
        public string Tagname { get; set; }
        public string TagIndex { get; set; }
    
        public virtual CollegeInfo CollegeInfo { get; set; }
    }
}
